import { Hono } from 'hono';
import businessesRoutes from './businesses.routes.ts';
import stationsRoutes from './stations.routes.ts';
import employeesRoutes from './employees.routes.ts';
import fundsRoutes from './funds.routes.ts';
import reportingRoutes from './reporting.routes.ts';
import workflowRoutes from './workflow.routes.ts';
import inventoryRoutes from './inventory.routes.ts';
import uiBuilderRoutes from './ui-builder.routes.ts';
import accountsRoutes from './accounts.routes.ts';
import partnersRoutes from './partners.routes.ts';
import pendingSettlementsRoutes from './pending-settlements.routes.ts';
import categoriesExpensesRoutes from './categories-expenses.routes.ts';
import operationTypesRoutes from './operation-types.routes.ts';
import journalEntriesRoutes from './journal-entries.routes.ts';
import billingConfigRoutes from './billing-config.routes.ts';
import warehouseRoutes from './warehouse.routes.ts';
import restRoutes from './api.rest.ts';

const api = new Hono();

api.route('/', businessesRoutes);
api.route('/', stationsRoutes);
api.route('/', employeesRoutes);
api.route('/', fundsRoutes);
api.route('/', reportingRoutes);
api.route('/', workflowRoutes);
api.route('/', inventoryRoutes);
api.route('/', uiBuilderRoutes);
api.route('/', accountsRoutes);
api.route('/', partnersRoutes);
api.route('/', pendingSettlementsRoutes);
api.route('/', categoriesExpensesRoutes);
api.route('/', operationTypesRoutes);
api.route('/', journalEntriesRoutes);
api.route('/', billingConfigRoutes);
api.route('/', warehouseRoutes);
api.route('/', restRoutes);

export default api;
