/**
 * فحص وجود كل الجداول والأعمدة المعرّفة في السكما مقابل قاعدة البيانات
 * تشغيل: npx tsx src/db/check-schema-match.ts
 */
import "dotenv/config";
import postgres from "postgres";

const connectionString =
  process.env.DATABASE_URL ||
  "postgresql://postgres:774424555@localhost:5432/hesabati";

// الجداول والأعمدة المتوقعة من السكما (core.ts) - أسماء الجداول والأعمدة كما في PostgreSQL
const expectedTables: Record<string, string[]> = {
  users: [
    "id",
    "username",
    "password",
    "full_name",
    "role",
    "is_active",
    "created_at",
    "updated_at",
  ],
  currencies: [
    "id",
    "code",
    "name_ar",
    "symbol",
    "exchange_rate",
    "is_default",
    "created_at",
  ],
  exchange_rates: [
    "id",
    "business_id",
    "from_currency_id",
    "to_currency_id",
    "rate",
    "effective_date",
    "source",
    "notes",
    "created_by",
    "created_at",
  ],
  roles: [
    "id",
    "business_id",
    "name",
    "description",
    "color",
    "max_voucher_amount",
    "max_daily_amount",
    "is_system",
    "is_active",
    "created_at",
    "updated_at",
  ],
  role_permissions: [
    "id",
    "role_id",
    "resource",
    "action",
    "constraints",
    "created_at",
  ],
  user_roles: [
    "id",
    "user_id",
    "role_id",
    "business_id",
    "assigned_by",
    "created_at",
  ],
  businesses: [
    "id",
    "name",
    "code",
    "type",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  business_partners: [
    "id",
    "business_id",
    "full_name",
    "share_percentage",
    "phone",
    "role",
    "notes",
    "is_active",
    "created_at",
  ],
  stations: [
    "id",
    "business_id",
    "name",
    "code",
    "location",
    "manager_id",
    "billing_systems",
    "has_employees",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  employees: [
    "id",
    "business_id",
    "full_name",
    "job_title",
    "station_id",
    "department",
    "salary",
    "salary_currency",
    "phone",
    "status",
    "hire_date",
    "monthly_allowance",
    "is_manager",
    "notes",
    "created_at",
    "updated_at",
  ],
  accounts: [
    "id",
    "business_id",
    "name",
    "account_type",
    "account_number",
    "provider",
    "sub_type",
    "sequence_number",
    "code",
    "responsible_person",
    "parent_account_id",
    "supported_currencies",
    "can_initiate_receipt",
    "can_initiate_payment",
    "can_receive_payment",
    "can_be_debited_by_receipt",
    "can_create_voucher",
    "can_approve_voucher",
    "receives_from_stations",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  account_allowed_links: [
    "id",
    "from_account_id",
    "to_account_id",
    "link_type",
    "is_active",
    "notes",
    "created_at",
  ],
  account_balances: [
    "id",
    "account_id",
    "currency_id",
    "balance",
    "updated_at",
  ],
  employee_billing_accounts: [
    "id",
    "employee_id",
    "station_id",
    "billing_system",
    "collection_method",
    "label",
    "sort_order",
    "is_active",
    "notes",
    "created_at",
  ],
  billing_systems_config: [
    "id",
    "business_id",
    "name",
    "icon",
    "color",
    "station_mode",
    "station_ids",
    "supported_method_ids",
    "sort_order",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  billing_account_types: [
    "id",
    "business_id",
    "name",
    "description",
    "icon",
    "sort_order",
    "is_active",
    "created_at",
  ],
  funds: [
    "id",
    "business_id",
    "name",
    "fund_type",
    "sub_type",
    "sequence_number",
    "code",
    "station_id",
    "responsible_person",
    "description",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  fund_balances: ["id", "fund_id", "currency_id", "balance", "updated_at"],
  suppliers: [
    "id",
    "business_id",
    "name",
    "category",
    "phone",
    "address",
    "contact_person",
    "notes",
    "is_active",
    "created_at",
    "updated_at",
  ],
  supplier_balances: [
    "id",
    "supplier_id",
    "currency_id",
    "balance",
    "updated_at",
  ],
  voucher_categories: [
    "id",
    "business_id",
    "name",
    "type",
    "parent_id",
    "icon",
    "color",
    "is_active",
    "created_at",
  ],
  vouchers: [
    "id",
    "business_id",
    "voucher_number",
    "voucher_type",
    "status",
    "amount",
    "currency_id",
    "exchange_rate",
    "from_account_id",
    "to_account_id",
    "from_fund_id",
    "to_fund_id",
    "station_id",
    "employee_id",
    "supplier_id",
    "category_id",
    "operation_type_id",
    "description",
    "reference",
    "voucher_date",
    "account_sequence",
    "template_sequence",
    "created_by",
    "approved_by",
    "reversal_status",
    "reversed_voucher_id",
    "reversal_reason",
    "reversed_at",
    "reversed_by",
    "created_at",
    "updated_at",
  ],
  attachments: [
    "id",
    "entity_type",
    "entity_id",
    "file_name",
    "file_path",
    "file_type",
    "file_size",
    "description",
    "uploaded_by",
    "created_at",
  ],
  daily_collections: [
    "id",
    "business_id",
    "station_id",
    "collection_date",
    "currency_id",
    "total_amount",
    "is_fully_delivered",
    "notes",
    "created_by",
    "created_at",
    "updated_at",
  ],
  collection_details: [
    "id",
    "collection_id",
    "employee_id",
    "billing_account_id",
    "amount",
    "notes",
    "created_at",
  ],
  delivery_records: [
    "id",
    "collection_id",
    "employee_id",
    "to_account_id",
    "amount",
    "currency_id",
    "delivery_date",
    "reference",
    "notes",
    "created_by",
    "created_at",
  ],
  expense_budget: [
    "id",
    "business_id",
    "name",
    "station_id",
    "amount",
    "currency_id",
    "expense_type",
    "month",
    "year",
    "notes",
    "created_at",
  ],
  salary_records: [
    "id",
    "business_id",
    "employee_id",
    "month",
    "year",
    "base_salary",
    "advance",
    "advance_date",
    "advance_paid_via",
    "deductions",
    "deduction_notes",
    "net_salary",
    "currency_id",
    "is_paid",
    "paid_date",
    "paid_via",
    "attendance_days",
    "notes",
    "created_at",
  ],
  warehouses: [
    "id",
    "business_id",
    "name",
    "warehouse_type",
    "sub_type",
    "sequence_number",
    "code",
    "station_id",
    "responsible_person",
    "location",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  inventory_items: [
    "id",
    "business_id",
    "name",
    "code",
    "category",
    "unit",
    "min_quantity",
    "notes",
    "is_active",
    "created_at",
  ],
  inventory_stock: [
    "id",
    "item_id",
    "warehouse_id",
    "quantity",
    "avg_cost",
    "costing_method",
    "cost_layers",
    "currency_id",
    "updated_at",
  ],
  inventory_movements: [
    "id",
    "business_id",
    "item_id",
    "warehouse_id",
    "movement_type",
    "quantity",
    "unit_cost",
    "currency_id",
    "to_warehouse_id",
    "supplier_id",
    "station_id",
    "reference",
    "description",
    "movement_date",
    "created_by",
    "created_at",
  ],
  reconciliations: [
    "id",
    "business_id",
    "title",
    "reconciliation_type",
    "status",
    "with_person",
    "account_id",
    "fund_id",
    "station_id",
    "employee_id",
    "supplier_id",
    "period_start",
    "period_end",
    "expected_amount",
    "actual_amount",
    "difference",
    "currency_id",
    "notes",
    "created_by",
    "created_at",
    "updated_at",
  ],
  pending_accounts: [
    "id",
    "business_id",
    "person_or_entity",
    "description",
    "status",
    "estimated_amount",
    "currency_id",
    "notes",
    "created_at",
    "updated_at",
  ],
  billing_periods: [
    "id",
    "business_id",
    "name",
    "station_id",
    "billing_system",
    "start_date",
    "end_date",
    "total_billed",
    "total_collected",
    "total_remaining",
    "currency_id",
    "is_closed",
    "closed_date",
    "notes",
    "created_at",
  ],
  diesel_consumption: [
    "id",
    "business_id",
    "station_id",
    "quantity",
    "unit",
    "consumption_date",
    "billing_period_id",
    "meter_reading",
    "notes",
    "created_by",
    "created_at",
  ],
  audit_log: [
    "id",
    "user_id",
    "business_id",
    "action",
    "table_name",
    "record_id",
    "old_data",
    "new_data",
    "ip_address",
    "created_at",
  ],
  expense_categories: [
    "id",
    "business_id",
    "name",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  operation_types: [
    "id",
    "business_id",
    "name",
    "description",
    "icon",
    "color",
    "category",
    "sequence_number",
    "code",
    "voucher_type",
    "payment_method",
    "source_account_id",
    "source_fund_id",
    "source_warehouse_id",
    "main_account_id",
    "main_fund_id",
    "template_type_id",
    "screens",
    "requires_attachment",
    "has_multi_lines",
    "workflow_config",
    "sort_order",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
  ],
  operation_type_accounts: [
    "id",
    "operation_type_id",
    "account_id",
    "employee_billing_account_id",
    "label",
    "permission",
    "sort_order",
    "is_active",
    "notes",
    "created_at",
  ],
  journal_entries: [
    "id",
    "business_id",
    "entry_number",
    "description",
    "entry_date",
    "reference",
    "operation_type_id",
    "category",
    "category_sequence",
    "template_sequence",
    "created_by",
    "is_balanced",
    "total_debit",
    "total_credit",
    "status",
    "created_at",
    "updated_at",
  ],
  journal_entry_lines: [
    "id",
    "journal_entry_id",
    "account_id",
    "line_type",
    "amount",
    "description",
    "sort_order",
    "created_at",
  ],
  sidebar_sections: [
    "id",
    "business_id",
    "name",
    "icon",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  sidebar_items: [
    "id",
    "section_id",
    "screen_key",
    "label",
    "icon",
    "route",
    "sort_order",
    "is_active",
    "badge",
    "badge_color",
    "created_at",
  ],
  user_sidebar_config: [
    "id",
    "user_id",
    "business_id",
    "sidebar_item_id",
    "is_visible",
    "custom_sort_order",
    "custom_section_name",
    "permission",
    "created_at",
    "updated_at",
  ],
  fund_types: [
    "id",
    "business_id",
    "name",
    "sub_type_key",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  bank_types: [
    "id",
    "business_id",
    "name",
    "sub_type_key",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  exchange_types: [
    "id",
    "business_id",
    "name",
    "sub_type_key",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  e_wallet_types: [
    "id",
    "business_id",
    "name",
    "sub_type_key",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  screen_templates: [
    "id",
    "business_id",
    "name",
    "description",
    "icon",
    "color",
    "layout_config",
    "template_key",
    "is_system",
    "is_active",
    "created_by",
    "created_at",
    "updated_at",
  ],
  screen_widgets: [
    "id",
    "screen_id",
    "widget_type",
    "title",
    "config",
    "position_x",
    "position_y",
    "width",
    "height",
    "sort_order",
    "is_visible",
    "created_at",
    "updated_at",
  ],
  screen_widget_templates: [
    "id",
    "widget_id",
    "operation_type_id",
    "sort_order",
    "created_at",
  ],
  screen_widget_accounts: [
    "id",
    "widget_id",
    "account_id",
    "sort_order",
    "created_at",
  ],
  screen_widget_warehouses: [
    "id",
    "widget_id",
    "warehouse_id",
    "sort_order",
    "created_at",
  ],
  screen_permissions: [
    "id",
    "screen_id",
    "user_id",
    "permission",
    "sort_order",
    "created_at",
    "updated_at",
  ],
  custom_screen_config: [
    "id",
    "screen_id",
    "tab1_label",
    "tab1_icon",
    "tab1_color",
    "tab1_operation_type_ids",
    "tab2_label",
    "tab2_icon",
    "tab2_color",
    "tab2_operation_type_ids",
    "history_label",
    "history_icon",
    "history_color",
    "accounts_section_label",
    "accounts_icon",
    "accounts_color",
    "account_ids",
    "created_at",
    "updated_at",
  ],
  sequence_counters: [
    "id",
    "business_id",
    "counter_type",
    "entity_id",
    "year",
    "last_number",
    "prefix",
    "created_at",
    "updated_at",
  ],
  warehouse_types: [
    "id",
    "business_id",
    "name",
    "sub_type_key",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  journal_entry_categories: [
    "id",
    "business_id",
    "name",
    "category_key",
    "description",
    "icon",
    "color",
    "sort_order",
    "is_active",
    "created_at",
    "updated_at",
  ],
  warehouse_operations: [
    "id",
    "business_id",
    "operation_number",
    "operation_type",
    "operation_type_id",
    "source_warehouse_id",
    "destination_warehouse_id",
    "related_operation_id",
    "related_voucher_id",
    "supplier_id",
    "total_cost",
    "total_items",
    "currency_id",
    "operation_date",
    "description",
    "reference",
    "status",
    "warehouse_sequence",
    "template_sequence",
    "created_by",
    "created_at",
    "updated_at",
  ],
  warehouse_operation_items: [
    "id",
    "operation_id",
    "item_name",
    "item_code",
    "quantity",
    "unit_cost",
    "total_cost",
    "unit",
    "currency_id",
    "notes",
    "sort_order",
    "created_at",
  ],
  analytics_snapshots: [
    "id",
    "business_id",
    "report_key",
    "filters_hash",
    "data",
    "generated_at",
    "expires_at",
    "created_by",
  ],
  workflow_transitions: [
    "id",
    "business_id",
    "operation_type_id",
    "from_status",
    "to_status",
    "action_name",
    "action_icon",
    "action_color",
    "required_role",
    "requires_note",
    "auto_execute",
    "sort_order",
    "is_active",
    "created_at",
  ],
  workflow_history: [
    "id",
    "business_id",
    "voucher_id",
    "transition_id",
    "from_status",
    "to_status",
    "action_name",
    "note",
    "executed_by",
    "executed_at",
  ],
  ui_data_sources: [
    "id",
    "business_id",
    "name",
    "source_type",
    "table_name",
    "query_template",
    "filters",
    "sorting",
    "config",
    "is_active",
    "created_at",
    "updated_at",
  ],
  ui_pages: [
    "id",
    "business_id",
    "page_key",
    "title",
    "description",
    "icon",
    "color",
    "layout",
    "config",
    "is_active",
    "sort_order",
    "created_by",
    "created_at",
    "updated_at",
  ],
  ui_components: [
    "id",
    "business_id",
    "page_id",
    "component_type",
    "title",
    "config",
    "data_source_id",
    "position_x",
    "position_y",
    "width",
    "height",
    "sort_order",
    "is_visible",
    "created_at",
    "updated_at",
  ],
};

interface ColumnDiff {
  table: string;
  missing: string[];
  extra: string[];
}

async function compareTableColumns(
  sql: ReturnType<typeof postgres>,
  table: string,
  expectedCols: string[],
): Promise<ColumnDiff | null> {
  const colsInDb = await sql`
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = ${table}
    ORDER BY ordinal_position
  `;
  const dbCols = new Set(
    (colsInDb as { column_name: string }[]).map((r) => r.column_name),
  );
  const expectedSet = new Set(expectedCols);
  const missingCols = expectedCols.filter((c) => !dbCols.has(c));
  const extraCols = [...dbCols].filter((c) => !expectedSet.has(c));
  if (missingCols.length || extraCols.length) {
    return { table, missing: missingCols, extra: extraCols };
  }
  return null;
}

function findExtraTables(dbTableNames: Set<string>): string[] {
  return [...dbTableNames].filter(
    (t) => !t.startsWith("__") && !expectedTables[t],
  );
}

function printResults(
  missing: string[],
  extraTables: string[],
  columnIssues: ColumnDiff[],
) {
  console.log(
    "\n=== فحص الجداول والأعمدة (السكما مقابل قاعدة البيانات) ===\n",
  );

  if (missing.length) {
    console.log("❌ جداول ناقصة في قاعدة البيانات:", missing.join(", "));
  } else {
    console.log("✅ كل الجداول المعرّفة في السكما موجودة في قاعدة البيانات.");
  }

  if (extraTables.length) {
    console.log(
      "ℹ️  جداول إضافية في DB (خارج السكما):",
      extraTables.join(", "),
    );
  }

  if (columnIssues.length) {
    console.log("\n❌ فروقات في الأعمدة:");
    for (const { table, missing: m, extra: e } of columnIssues) {
      if (m.length)
        console.log("   " + table + ": أعمدة ناقصة: " + m.join(", "));
      if (e.length)
        console.log("   " + table + ": أعمدة زائدة في DB: " + e.join(", "));
    }
  } else if (!missing.length) {
    console.log("✅ كل الأعمدة المتوقعة موجودة ولا توجد أعمدة ناقصة.");
  }

  console.log("");
}

async function main() {
  const sql = postgres(connectionString, { max: 1 });
  const missing: string[] = [];
  const columnIssues: ColumnDiff[] = [];

  try {
    const tablesInDb = await sql`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `;
    const dbTableNames = new Set(
      (tablesInDb as { table_name: string }[]).map((r) => r.table_name),
    );

    for (const [table, expectedCols] of Object.entries(expectedTables)) {
      if (!dbTableNames.has(table)) {
        missing.push(table);
        continue;
      }
      const diff = await compareTableColumns(sql, table, expectedCols);
      if (diff) columnIssues.push(diff);
    }

    const extraTables = findExtraTables(dbTableNames);
    printResults(missing, extraTables, columnIssues);
  } finally {
    await sql.end();
  }
}

try {
  await main();
} catch (e: unknown) {
  const message = e instanceof Error ? e.message : JSON.stringify(e);
  console.error("خطأ في الاتصال بقاعدة البيانات:", message);
  process.exit(1);
}
